[supervisord]
nodaemon=true

[program:mysql]
command=/usr/bin/mysqld_safe
autostart=true
autorestart=true

[program:yii]
directory=/app
command=php yii serve --host=0.0.0.0 --port=8080
autostart=true
autorestart=true
